#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -o interactive ]]
then
  # Colors are hardcoded in prezto - https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/init.zsh
  # export LSCOLORS='dxgxcxdxcxegedabagacad'
  # export LS_COLORS='dxgxcxdxcxegedabagacad'
  export REPORTTIME=10
fi
