if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias atom=atom-beta
alias bert="bundle exec rake test"
alias console="bundle exec rails console"
alias consoleprod="bundle exec rails console production_ro"
alias consoleprodrw="bundle exec rails console production"
alias env="env | sort"
alias gitconfig="git config user.email \"david_jacques@cable.comcast.com\"; git config user.name \"David Jacques\""
alias migrate="bundle exec rake db:migrate"
alias migration="bundle exec rails generate migration"
alias migratetest="bundle exec rake db:test:prepare"
alias nom="rm -rf node_modules && npm cache clear && npm i"
alias redis-browser="redis-browser --config ~/Box\ Sync/Config/redis-browser.yml"
alias remigrate="bundle exec rake db:rollback && bundle exec rake db:migrate"
alias rollback="bundle exec rake db:rollback"
alias runner="bundle exec rails runner"
alias test="bundle exec ruby -Itest -Ilib"
alias tests="bundle exec rake test"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

function chpwd() {
  emulate -L zsh
  [ -f .nvmrc ] && nvm use
}

export EDITOR=vim

export NVM_DIR="/Users/djacqu001/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

unsetopt AUTO_NAME_DIRS
